<?php

// Data functions for table employment_and_income_history

// This script and data application were generated by AppGini 5.31
// Download AppGini for free from http://bigprof.com/appgini/download/

function employment_and_income_history_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('employment_and_income_history');
	if(!$arrPerm[1]){
		return false;
	}

	$data['tenant'] = makeSafe($_POST['tenant']);
		if($data['tenant'] == empty_lookup_value){ $data['tenant'] = ''; }
	$data['employer_name'] = makeSafe($_POST['employer_name']);
		if($data['employer_name'] == empty_lookup_value){ $data['employer_name'] = ''; }
	$data['city'] = makeSafe($_POST['city']);
		if($data['city'] == empty_lookup_value){ $data['city'] = ''; }
	$data['employer_phone'] = makeSafe($_POST['employer_phone']);
		if($data['employer_phone'] == empty_lookup_value){ $data['employer_phone'] = ''; }
	$data['employed_from'] = intval($_POST['employed_fromYear']) . '-' . intval($_POST['employed_fromMonth']) . '-' . intval($_POST['employed_fromDay']);
	$data['employed_from'] = parseMySQLDate($data['employed_from'], '');
	$data['employed_till'] = intval($_POST['employed_tillYear']) . '-' . intval($_POST['employed_tillMonth']) . '-' . intval($_POST['employed_tillDay']);
	$data['employed_till'] = parseMySQLDate($data['employed_till'], '');
	$data['occupation'] = makeSafe($_POST['occupation']);
		if($data['occupation'] == empty_lookup_value){ $data['occupation'] = ''; }
	$data['notes'] = makeSafe($_POST['notes']);
		if($data['notes'] == empty_lookup_value){ $data['notes'] = ''; }

	// hook: employment_and_income_history_before_insert
	if(function_exists('employment_and_income_history_before_insert')){
		$args=array();
		if(!employment_and_income_history_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `employment_and_income_history` set       `tenant`=' . (($data['tenant'] !== '' && $data['tenant'] !== NULL) ? "'{$data['tenant']}'" : 'NULL') . ', `employer_name`=' . (($data['employer_name'] !== '' && $data['employer_name'] !== NULL) ? "'{$data['employer_name']}'" : 'NULL') . ', `city`=' . (($data['city'] !== '' && $data['city'] !== NULL) ? "'{$data['city']}'" : 'NULL') . ', `employer_phone`=' . (($data['employer_phone'] !== '' && $data['employer_phone'] !== NULL) ? "'{$data['employer_phone']}'" : 'NULL') . ', `employed_from`=' . (($data['employed_from'] !== '' && $data['employed_from'] !== NULL) ? "'{$data['employed_from']}'" : 'NULL') . ', `employed_till`=' . (($data['employed_till'] !== '' && $data['employed_till'] !== NULL) ? "'{$data['employed_till']}'" : 'NULL') . ', `occupation`=' . (($data['occupation'] !== '' && $data['occupation'] !== NULL) ? "'{$data['occupation']}'" : 'NULL') . ', `notes`=' . (($data['notes'] !== '' && $data['notes'] !== NULL) ? "'{$data['notes']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"employment_and_income_history_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=db_insert_id(db_link());

	// hook: employment_and_income_history_after_insert
	if(function_exists('employment_and_income_history_after_insert')){
		$res = sql("select * from `employment_and_income_history` where `id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!employment_and_income_history_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='employment_and_income_history', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function employment_and_income_history_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('employment_and_income_history');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='employment_and_income_history' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='employment_and_income_history' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: employment_and_income_history_before_delete
	if(function_exists('employment_and_income_history_before_delete')){
		$args=array();
		if(!employment_and_income_history_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `employment_and_income_history` where `id`='$selected_id'", $eo);

	// hook: employment_and_income_history_after_delete
	if(function_exists('employment_and_income_history_after_delete')){
		$args=array();
		employment_and_income_history_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='employment_and_income_history' and pkValue='$selected_id'", $eo);
}

function employment_and_income_history_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('employment_and_income_history');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='employment_and_income_history' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='employment_and_income_history' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['tenant'] = makeSafe($_POST['tenant']);
		if($data['tenant'] == empty_lookup_value){ $data['tenant'] = ''; }
	$data['employer_name'] = makeSafe($_POST['employer_name']);
		if($data['employer_name'] == empty_lookup_value){ $data['employer_name'] = ''; }
	$data['city'] = makeSafe($_POST['city']);
		if($data['city'] == empty_lookup_value){ $data['city'] = ''; }
	$data['employer_phone'] = makeSafe($_POST['employer_phone']);
		if($data['employer_phone'] == empty_lookup_value){ $data['employer_phone'] = ''; }
	$data['employed_from'] = intval($_POST['employed_fromYear']) . '-' . intval($_POST['employed_fromMonth']) . '-' . intval($_POST['employed_fromDay']);
	$data['employed_from'] = parseMySQLDate($data['employed_from'], '');
	$data['employed_till'] = intval($_POST['employed_tillYear']) . '-' . intval($_POST['employed_tillMonth']) . '-' . intval($_POST['employed_tillDay']);
	$data['employed_till'] = parseMySQLDate($data['employed_till'], '');
	$data['occupation'] = makeSafe($_POST['occupation']);
		if($data['occupation'] == empty_lookup_value){ $data['occupation'] = ''; }
	$data['notes'] = makeSafe($_POST['notes']);
		if($data['notes'] == empty_lookup_value){ $data['notes'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: employment_and_income_history_before_update
	if(function_exists('employment_and_income_history_before_update')){
		$args=array();
		if(!employment_and_income_history_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `employment_and_income_history` set       `tenant`=' . (($data['tenant'] !== '' && $data['tenant'] !== NULL) ? "'{$data['tenant']}'" : 'NULL') . ', `employer_name`=' . (($data['employer_name'] !== '' && $data['employer_name'] !== NULL) ? "'{$data['employer_name']}'" : 'NULL') . ', `city`=' . (($data['city'] !== '' && $data['city'] !== NULL) ? "'{$data['city']}'" : 'NULL') . ', `employer_phone`=' . (($data['employer_phone'] !== '' && $data['employer_phone'] !== NULL) ? "'{$data['employer_phone']}'" : 'NULL') . ', `employed_from`=' . (($data['employed_from'] !== '' && $data['employed_from'] !== NULL) ? "'{$data['employed_from']}'" : 'NULL') . ', `employed_till`=' . (($data['employed_till'] !== '' && $data['employed_till'] !== NULL) ? "'{$data['employed_till']}'" : 'NULL') . ', `occupation`=' . (($data['occupation'] !== '' && $data['occupation'] !== NULL) ? "'{$data['occupation']}'" : 'NULL') . ', `notes`=' . (($data['notes'] !== '' && $data['notes'] !== NULL) ? "'{$data['notes']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="employment_and_income_history_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: employment_and_income_history_after_update
	if(function_exists('employment_and_income_history_after_update')){
		$res = sql("SELECT * FROM `employment_and_income_history` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!employment_and_income_history_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='employment_and_income_history' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function employment_and_income_history_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('employment_and_income_history');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_tenant = thisOr(undo_magic_quotes($_REQUEST['filterer_tenant']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: tenant
	$combo_tenant = new DataCombo;
	// combobox: employed_from
	$combo_employed_from = new DateCombo;
	$combo_employed_from->DateFormat = "mdy";
	$combo_employed_from->MinYear = 1900;
	$combo_employed_from->MaxYear = 2100;
	$combo_employed_from->DefaultDate = parseMySQLDate('', '');
	$combo_employed_from->MonthNames = $Translation['month names'];
	$combo_employed_from->NamePrefix = 'employed_from';
	// combobox: employed_till
	$combo_employed_till = new DateCombo;
	$combo_employed_till->DateFormat = "mdy";
	$combo_employed_till->MinYear = 1900;
	$combo_employed_till->MaxYear = 2100;
	$combo_employed_till->DefaultDate = parseMySQLDate('', '');
	$combo_employed_till->MonthNames = $Translation['month names'];
	$combo_employed_till->NamePrefix = 'employed_till';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='employment_and_income_history' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='employment_and_income_history' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `employment_and_income_history` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_tenant->SelectedData = $row['tenant'];
		$combo_employed_from->DefaultDate = $row['employed_from'];
		$combo_employed_till->DefaultDate = $row['employed_till'];
	}else{
		$combo_tenant->SelectedData = $filterer_tenant;
	}
	$combo_tenant->HTML = '<span id="tenant-container' . $rnd1 . '"></span><input type="hidden" name="tenant" id="tenant' . $rnd1 . '">';
	$combo_tenant->MatchText = '<span id="tenant-container-readonly' . $rnd1 . '"></span><input type="hidden" name="tenant" id="tenant' . $rnd1 . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_tenant__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['tenant'] : $filterer_tenant); ?>"};

		jQuery(function() {
			tenant_reload__RAND__();
		});
		function tenant_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#tenant-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_tenant__RAND__.value, t: 'employment_and_income_history', f: 'tenant' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="tenant"]').val(resp.results[0].id);
						jQuery('[id=tenant-container-readonly__RAND__]').html('<span id="tenant-match-text">' + resp.results[0].text + '</span>');


						if(typeof(tenant_update_autofills__RAND__) == 'function') tenant_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'employment_and_income_history', f: 'tenant' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_tenant__RAND__.value = e.added.id;
				current_tenant__RAND__.text = e.added.text;
				jQuery('[name="tenant"]').val(e.added.id);


				if(typeof(tenant_update_autofills__RAND__) == 'function') tenant_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_tenant__RAND__.value, t: 'employment_and_income_history', f: 'tenant' }
			}).done(function(resp){
				jQuery('[id=tenant-container__RAND__], [id=tenant-container-readonly__RAND__]').html('<span id="tenant-match-text">' + resp.results[0].text + '</span>');

				if(typeof(tenant_update_autofills__RAND__) == 'function') tenant_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/employment_and_income_history_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/employment_and_income_history_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Employment and income history details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return employment_and_income_history_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return employment_and_income_history_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return employment_and_income_history_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#tenant').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#tenant_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#employer_name').replaceWith('<p class=\"form-control-static\" id=\"employer_name\">' + (jQuery('#employer_name').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#city').replaceWith('<p class=\"form-control-static\" id=\"city\">' + (jQuery('#city').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#employer_phone').replaceWith('<p class=\"form-control-static\" id=\"employer_phone\">' + (jQuery('#employer_phone').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#employed_from').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#employed_fromDay, #employed_fromMonth, #employed_fromYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#employed_till').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#employed_tillDay, #employed_tillMonth, #employed_tillYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#occupation').replaceWith('<p class=\"form-control-static\" id=\"occupation\">' + (jQuery('#occupation').val() || '') + '</p>');\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(tenant)%%>', $combo_tenant->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(tenant)%%>', $combo_tenant->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(tenant)%%>', urlencode($combo_tenant->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(employed_from)%%>', ($selected_id && !$arrPerm[3] ? '<p class="form-control-static">' . $combo_employed_from->GetHTML(true) . '</p>' : $combo_employed_from->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(employed_from)%%>', $combo_employed_from->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(employed_till)%%>', ($selected_id && !$arrPerm[3] ? '<p class="form-control-static">' . $combo_employed_till->GetHTML(true) . '</p>' : $combo_employed_till->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(employed_till)%%>', $combo_employed_till->GetHTML(true), $templateCode);

	// process foreign key links
	if($selected_id){
		$templateCode=str_replace('<%%PLINK(tenant)%%>', ($combo_tenant->SelectedData ? "<span id=\"applicants_and_tenants_plink1\" class=\"hidden\"><a class=\"btn btn-default\" href=\"applicants_and_tenants_view.php?SelectedID=" . urlencode($combo_tenant->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(tenant)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(employer_name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(city)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(employer_phone)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(employed_from)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(employed_till)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(occupation)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(notes)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(tenant)%%>', htmlspecialchars($row['tenant'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(tenant)%%>', urlencode($urow['tenant']), $templateCode);
		$templateCode=str_replace('<%%VALUE(employer_name)%%>', htmlspecialchars($row['employer_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(employer_name)%%>', urlencode($urow['employer_name']), $templateCode);
		$templateCode=str_replace('<%%VALUE(city)%%>', htmlspecialchars($row['city'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(city)%%>', urlencode($urow['city']), $templateCode);
		$templateCode=str_replace('<%%VALUE(employer_phone)%%>', htmlspecialchars($row['employer_phone'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(employer_phone)%%>', urlencode($urow['employer_phone']), $templateCode);
		$templateCode=str_replace('<%%VALUE(employed_from)%%>', @date('m/d/Y', @strtotime(htmlspecialchars($row['employed_from'], ENT_QUOTES))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(employed_from)%%>', urlencode(@date('m/d/Y', @strtotime(htmlspecialchars($urow['employed_from'], ENT_QUOTES)))), $templateCode);
		$templateCode=str_replace('<%%VALUE(employed_till)%%>', @date('m/d/Y', @strtotime(htmlspecialchars($row['employed_till'], ENT_QUOTES))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(employed_till)%%>', urlencode(@date('m/d/Y', @strtotime(htmlspecialchars($urow['employed_till'], ENT_QUOTES)))), $templateCode);
		$templateCode=str_replace('<%%VALUE(occupation)%%>', htmlspecialchars($row['occupation'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(occupation)%%>', urlencode($urow['occupation']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode=str_replace('<%%HTMLAREA(notes)%%>', '<textarea name="notes" id="notes" rows="5">'.htmlspecialchars($row['notes'], ENT_QUOTES).'</textarea>', $templateCode);
		}else{
			$templateCode=str_replace('<%%HTMLAREA(notes)%%>', $row['notes'], $templateCode);
		}
		$templateCode=str_replace('<%%VALUE(notes)%%>', nl2br($row['notes']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(notes)%%>', urlencode($urow['notes']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(tenant)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(tenant)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(employer_name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(employer_name)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(city)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(city)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(employer_phone)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(employer_phone)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(employed_from)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(employed_from)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(employed_till)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(employed_till)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(occupation)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(occupation)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%HTMLAREA(notes)%%>', '<textarea name="notes" id="notes" rows="5"></textarea>', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: employment_and_income_history_dv
	if(function_exists('employment_and_income_history_dv')){
		$args=array();
		employment_and_income_history_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>